"""add accreditation_checks

Revision ID: 70b14679f2a2
Revises: ef75c31cccc1
Create Date: 2026-04-30 20:15:29.529743
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "70b14679f2a2"
down_revision: str | None = "ef75c31cccc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accreditation_checks",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider_name", sa.String(length=32), nullable=False),
        sa.Column("provider_reference", sa.String(length=128), nullable=True),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_accreditation_checks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accreditation_checks")),
    )
    op.create_index("ix_accreditation_status", "accreditation_checks", ["status"], unique=False)
    op.create_index(
        "ix_accreditation_user_id_attempt",
        "accreditation_checks",
        ["user_id", "attempt_number"],
        unique=False,
    )
    op.create_index(
        "ix_accreditation_user_id_created_at",
        "accreditation_checks",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_accreditation_user_id_created_at", table_name="accreditation_checks")
    op.drop_index("ix_accreditation_user_id_attempt", table_name="accreditation_checks")
    op.drop_index("ix_accreditation_status", table_name="accreditation_checks")
    op.drop_table("accreditation_checks")
    # ### end Alembic commands ###
